### ISSUE TITLE
random fatal errors on app run

### ISSUE THREAD

**Issue by ayhangenc** [bitfocus/gondi#1]
Hi,

While I'm testing the example code receivesend.go (renamed to ndi.go locally) I'm getting random fatal errors on app run. The platform is Mac OS Ventura 13.4. The source is NDI HX CAM on iPhone. Sometimes it runs fine, sometime it crash at startup. The log is attached.
I run with
`` 
go run ndi.go 
``
and considering the error is related cgo alternatively I run with 
``
CGO_ENABLED=0 go run ndi.go. 
``
both case, I have fatal error randomly.
Tha latest NDI SDK and NDI Apps are installed before testing.

Thanks

```

anyuser@any-mb sil % go run ndi.go
Initializing NDI
NDI version: NDI SDK APPLE 09:59:09 Feb  2 2023 5.5.3
Looking for sources...
numSources: 1
Source selected: Kizil (NDI HX Camera)
Total video frames received: 0, total dropped: 0
Total audio frames received: 0, total dropped: 0
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x7 addr=0x2ab52874 pc=0x2ab52874]

runtime stack:
runtime.throw({0x10c23c7?, 0x391d6238?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7000046aed40 sp=0x7000046aed10 pc=0x1030d9d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7000046aeda0 sp=0x7000046aed40 pc=0x1045449

goroutine 6 [syscall]:
runtime.cgocall(0x109a340, 0xc00014f970)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0001846e8 sp=0xc0001846b0 pc=0x1003d5c
github.com/ebitengine/purego.RegisterFunc.func1({0xc00011d7d0?, 0x2?, 0x2?})
        /Users/anyuser/go/pkg/mod/github.com/ebitengine/purego@v0.3.2/func.go:188 +0xc45 fp=0xc0001849e8 sp=0xc0001846e8 pc=0x1099125
reflect.callReflect(0xc00011ca50, 0xc000184f50, 0xc000184e28, 0xc000184e30)
        /usr/local/go/src/reflect/value.go:772 +0x56d fp=0xc000184dd8 sp=0xc0001849e8 pc=0x1077bcd
reflect.callReflect(0xc00011ca50, 0xc000184f50, 0xc000184e28, 0xc000184e30)
        <autogenerated>:1 +0x4b fp=0xc000184e08 sp=0xc000184dd8 pc=0x107d0eb
reflect.makeFuncStub()
        /usr/local/go/src/reflect/asm_amd64.s:47 +0x7a fp=0xc000184f50 sp=0xc000184e08 pc=0x107c01a
github.com/bitfocus/gondi.(*SendInstance).SendAudioFrame(...)
        /Users/anyuser/go/pkg/mod/github.com/bitfocus/gondi@v0.0.2/send.go:160
main.captureAndSendAudio(0xc000016050, 0xc000016060)
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:28 +0xad fp=0xc000184fc0 sp=0xc000184f50 pc=0x109e44d
main.main.func5()
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:89 +0x2a fp=0xc000184fe0 sp=0xc000184fc0 pc=0x109eb4a
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000184fe8 sp=0xc000184fe0 pc=0x105f1a1
created by main.main
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:89 +0x472

goroutine 1 [sleep]:
runtime.gopark(0x8b7d991edcb?, 0x2?, 0x31?, 0x0?, 0xc000126b60?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00013ddc0 sp=0xc00013dda0 pc=0x1033a56
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:195 +0x135 fp=0xc00013de00 sp=0xc00013ddc0 pc=0x105c055
main.main()
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:96 +0x5a6 fp=0xc00013df80 sp=0xc00013de00 pc=0x109ea66
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc00013dfe0 sp=0xc00013df80 pc=0x1033627
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00013dfe8 sp=0xc00013dfe0 pc=0x105f1a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003afb0 sp=0xc00003af90 pc=0x1033a56
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc00003afe0 sp=0xc00003afb0 pc=0x1033890
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003afe8 sp=0xc00003afe0 pc=0x105f1a1
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003b780 sp=0xc00003b760 pc=0x1033a56
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00003b7c8 sp=0xc00003b780 pc=0x102100e
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00003b7e0 sp=0xc00003b7c8 pc=0x1016286
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003b7e8 sp=0xc00003b7e0 pc=0x105f1a1
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000060000?, 0x10db868?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003bf70 sp=0xc00003bf50 pc=0x1033a56
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x11639c0)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00003bfa0 sp=0xc00003bf70 pc=0x101eef3
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc00003bfc8 sp=0xc00003bfa0 pc=0x101f4c5
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00003bfe0 sp=0xc00003bfc8 pc=0x1016226
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003bfe8 sp=0xc00003bfe0 pc=0x105f1a1
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x1163e00?, 0xe0?, 0x24?, 0xc00003a770?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003a628 sp=0xc00003a608 pc=0x1033a56
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00003a7e0 sp=0xc00003a628 pc=0x10152c7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003a7e8 sp=0xc00003a7e0 pc=0x105f1a1
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x45

goroutine 5 [syscall]:
runtime.cgocall(0x109a340, 0xc00014f8c0)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000486d8 sp=0xc0000486a0 pc=0x1003d5c
github.com/ebitengine/purego.RegisterFunc.func1({0xc000154100?, 0x5?, 0x8?})
        /Users/anyuser/go/pkg/mod/github.com/ebitengine/purego@v0.3.2/func.go:188 +0xc45 fp=0xc0000489d8 sp=0xc0000486d8 pc=0x1099125
reflect.callReflect(0xc00011d380, 0xc000048f40, 0xc000048e18, 0xc000048e20)
        /usr/local/go/src/reflect/value.go:772 +0x56d fp=0xc000048dc8 sp=0xc0000489d8 pc=0x1077bcd
reflect.callReflect(0xc00011d380, 0xc000048f40, 0xc000048e18, 0xc000048e20)
        <autogenerated>:1 +0x4b fp=0xc000048df8 sp=0xc000048dc8 pc=0x107d0eb
reflect.makeFuncStub()
        /usr/local/go/src/reflect/asm_amd64.s:47 +0x7a fp=0xc000048f40 sp=0xc000048df8 pc=0x107c01a
github.com/bitfocus/gondi.(*RecvInstance).CaptureV2(...)
        /Users/anyuser/go/pkg/mod/github.com/bitfocus/gondi@v0.0.2/recv.go:47
main.captureAndSendVideo(0xc000016050, 0xc000016060)
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:13 +0xdb fp=0xc000048fc0 sp=0xc000048f40 pc=0x109e2fb
main.main.func4()
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:88 +0x2a fp=0xc000048fe0 sp=0xc000048fc0 pc=0x109ebaa
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000048fe8 sp=0xc000048fe0 pc=0x105f1a1
created by main.main
        /Users/anyuser/GolandProjects/X.7/sil/ndi.go:88 +0x41e
exit status 2
anyuser@any-mb sil % 

```

**Comment by haakonnessjoen** [comment]
Have you done anything else than renaming the example file? Any code changes?

The example code is very raw. In theory, the send functions should wait for the frame to be sent before returning, so that the free call should in theory be all right. But maybe it is related to freeing the frame before it is done with using it. You could try to add a tiny buffer of frames, and then free them after you have sent one more frame. And see if that has anything to do with it.

I haven't tried with NDI HX at all, so not iPhone camera either. Maybe it only happens with NDI HX. I could try it out some time this week if you don't figure it out. But the library interface shouldn't really care about this.

Does it always happen when you are starting the program? Maybe there is something weird with the first video or audio frame it receives. Maybe you could try debugging the frame objects.

**Comment by ayhangenc** [comment]
I'll try your suggestions. 
The code is copy paste from github, I'll try to add some control and would test with a basic source. It's not always happening, so I guess it's related with the initialization of the reception of the stream. If it starts fine then no problem during execution.
I'll update as necessary...

**Comment by ayhangenc** [comment]
Tested with NDI Scan Converter App and there is no error, it's probably something related to NDI HX and/or iOS HX Camera app.
I'll work on that.
Better to close this now.
Thanks
